coverage:
  status:
    patch:
      default:
        target: 60%
    project:
      unit:
        target: 80%
        flags: [unit]
      integration:
        target: 65%
        flags: [ integration ]

comment:
  layout: "diff, flags, files"
  behavior: default
