name: security

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "fix/**"
    paths:
      - "go.mod"
      - "go.sum"
      - "**/*.go"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at 00:00
  workflow_call:
  workflow_dispatch:

permissions: write-all

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "stable"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: go.sum

      - name: Setup xc
        uses: joerdav/setup-xc@v0.0.3

      - name: Setup deps
        run: |
          xc setup:deps

      - name: Setup Go env
        run: |
          xc setup:goenv

      - name: Go Generate
        run: |
          xc setup:mocks
          git diff --exit-code

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
